backend:
  name: github
  repo: agtz92/soynuevo
  branch: main

media_folder: static/assets
public_folder: /assets

collections:
  - name: blog
    label: Blog
    folder: blog
    create: true
    fields:
      - { name: title, label: Title, hint: Nombre del post debe empezar con "Cómo " ej. Como Pescar Lobina en Agua Dulce }
      - { name: slug, label: Slug, hint: Debe ser el nombre del post con guiones. ej. como-pescar-lobina-en-agua-dulce }
      - { name: date, label: Date, widget: datetime }
      - { collection: dificultad, valueField: nivel, searchFields: ["nivel"], displayFields: ["nivel"], widget: relation, name: dificultad, label: Nivel de Dificultad, required: true, multiple: false, hint: Poner nivel de dificultad. Campo obligatorio}
      - { collection: categoria, valueField: categoria, searchFields: ["categoria"], displayFields: ["categoria"], widget: relation, name: categoria, label: Categoría Principal, required: true, multiple: false, hint: Poner categoría prinicpal. Campo obligatorio}
      - { collection: tags, valueField: tag, searchFields: ["tag"], displayFields: ["tag"], widget: relation, name: tags, label: Tags, required: true, multiple: true, hint: Tags para identificar el artículo. Campo obligatorio}
      - { name: body, label: Body, widget: markdown, mode: rich_text, hint: Estructura debe ser parrafo -> imagen/video -> parrafo -> imagen/video -> parrafo}
      
     
  - name: dificultad
    label: Niveles de Dificultad
    folder: cms/dificultad
    create: false
    slug: "{{slug}}"
    fields:
      - {widget: string, name: nivel, label: Nivel de dificultad, required: true, hint: Nivel de dificultad }
  - name: categoria
    label: Categoria
    folder: cms/categorias
    create: false
    slug: "{{slug}}"
    fields:
      - {widget: string, name: categoria, label: Categoria, required: true, hint: Categoria principal }
  - name: tags
    label: Tags
    folder: cms/tags
    create: true
    slug: "{{slug}}"
    fields:
      - {widget: string, name: tag, label: Tags, required: true, hint: nombre del tag }